# GET request
POST http://localhost:3000/api/category
Content-Type: application/json

{
    "name": "Laptop"
}

###

# POST request
POST http://localhost:3000/api/item
Content-Type: application/json

{
    "name": "hp pavillion",
    "attributes": [
        {
            "name": "make",
            "required": 1
        },
        {
            "name": "model",
            "required": 1
        }
    ],
    "category_id": 1
}

###

# GET request
GET http://localhost:3000/api/item/search?q=hp
Content-Accept: application/json

###

# GET request
GET http://localhost:3000/api/category/search?q=laptop
Accept: application/json

###

# GET request
GET http://localhost:3000/api/item/1
Accept: application/json

###

# POST request
POST http://localhost:3000/api/item/variation
Content-Type: application/json

{
    "item_id": 1,
    "attributeValues": [
        {
            "id": 1
        }
    ],
    "quantity": 50
}

###

# GET request
GET http://localhost:3000/api/item/stock/1
Accept: application/json

###

POST http://localhost:3000/api/loan/grant?stock_id=1&emp_id=1

###
POST http://localhost:3000/api/loan/revoke?stock_id=1

###
GET http://localhost:3000/api/loan/history/stock/1
Accept: application/json

###
GET http://localhost:3000/api/loan/history/employee/1
Accept: application/json
